# 2022년 1월의 도서 판매 데이터를 기준
# 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가)
# 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트
# 저자 ID 오름차순 / 카테고리 내림차순

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS 'TOTAL_SALES'
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022
AND MONTH(S.SALES_DATE) = 1
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC