SELECT D.ID
FROM (
    SELECT B.ID
    FROM ECOLI_DATA A
    LEFT OUTER JOIN ECOLI_DATA B
    ON A.ID = B.PARENT_ID
    WHERE A.PARENT_ID IS NULL
) C
LEFT OUTER JOIN ECOLI_DATA D
ON C.ID = D.PARENT_ID
WHERE D.ID IS NOT NULL
ORDER BY D.ID