SELECT *
FROM (
    SELECT DATE_FORMAT(N.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, N.PRODUCT_ID, N.USER_ID, N.SALES_AMOUNT
    FROM ONLINE_SALE N
    WHERE N.SALES_DATE LIKE '2022-03-%'
    UNION ALL
    SELECT DATE_FORMAT(F.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, F.PRODUCT_ID, NULL AS 'USER_ID', F.SALES_AMOUNT
    FROM OFFLINE_SALE F
    WHERE F.SALES_DATE LIKE '2022-03-%'
) A
ORDER BY A.SALES_DATE, A.PRODUCT_ID, A.USER_ID;