# 자동차 종류가 '세단' 또는 'SUV'
# 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
# 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
# 대여금액 내림차순, 자동차종류 오름차순, 자동차ID 내림차순

WITH AVILABLE_RENT_CAR AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE < '2022-11-30'
        AND END_DATE > '2022-11-01'
        GROUP BY CAR_ID
    )
)
, CAR_DISCOUNT AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV')
    AND DURATION_TYPE = '30일 이상'
)
SELECT
    C.CAR_ID
    , C.CAR_TYPE
    , ROUND(C.DAILY_FEE * 30 * ((100 - D.DISCOUNT_RATE) / 100), 0) AS 'FEE'
FROM CAR_RENTAL_COMPANY_CAR C
RIGHT OUTER JOIN AVILABLE_RENT_CAR AR ON C.CAR_ID = AR.CAR_ID
LEFT OUTER JOIN CAR_DISCOUNT D ON C.CAR_TYPE = D.CAR_TYPE
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
AND C.DAILY_FEE * 30 * ((100 - D.DISCOUNT_RATE) / 100) >= 500000
AND C.DAILY_FEE * 30 * ((100 - D.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC