# 2021년에 가입한 전체 회원
WITH JOIN_2021 AS (
    SELECT COUNT(*) AS USERS
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
# 2021년 가입한 회원 중 상품을 구매한 회원
PUCHASED AS (
    SELECT YEAR(SALES_DATE) AS 'YEAR', MONTH(SALES_DATE) AS 'MONTH', COUNT(DISTINCT(O.USER_ID)) AS 'PUCHASED_USERS'
    FROM ONLINE_SALE O
    INNER JOIN USER_INFO U
    ON O.USER_ID = U.USER_ID
    WHERE YEAR(U.JOINED) = 2021
    GROUP BY YEAR, MONTH
)
SELECT P.YEAR, P.MONTH, P.PUCHASED_USERS, ROUND(P.PUCHASED_USERS / (SELECT * FROM JOIN_2021), 1) AS 'PUCHASED_RATIO'
FROM PUCHASED P
ORDER BY 1, 2