# 대여 중인 자동차들의 정보 CAR_RENTAL_COMPANY_CAR
# 자동차 대여 기록 정보 CAR_RENTAL_COMPANY_RENTAL_HISTORY
# 자동차 종류 별/대여 기간 종류 별 할인 정책 정보 CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# 
# 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해
# 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력
# 대여 금액 내림차순, 대여 기록 ID 내림차순

SELECT
    A.HISTORY_ID
    , IF(
        P.DISCOUNT_RATE IS NULL
        , A.FEE
        , ROUND(A.FEE * (1 - (P.DISCOUNT_RATE * 0.01)), 0)
    ) AS FEE
FROM (
    SELECT
        H.HISTORY_ID
        , C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) AS 'FEE'
        , CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 7 AND DATEDIFF(H.END_DATE, H.START_DATE) < 30 THEN '7일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 30 AND DATEDIFF(H.END_DATE, H.START_DATE) < 90 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 90 THEN '90일 이상'
            ELSE NULL
        END AS 'DURATION_TYPE'
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    INNER JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    WHERE CAR_TYPE = '트럭'
    GROUP BY H.HISTORY_ID
) A
LEFT JOIN (
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) P
ON A.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, A.HISTORY_ID DESC