WITH RECURSIVE TIME_CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME_CTE
    WHERE HOUR < 23
)
SELECT TIME_CTE.HOUR, COUNT(O.ANIMAL_ID) AS 'COUNT'
FROM TIME_CTE
LEFT OUTER JOIN ANIMAL_OUTS O
ON TIME_CTE.HOUR = HOUR(O.DATETIME)
GROUP BY TIME_CTE.HOUR
ORDER BY TIME_CTE.HOUR