SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM REST_REVIEW R
LEFT OUTER JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT COUNT(*) AS 'REVIEW_COUNT'
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY 1 DESC
        LIMIT 1
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT