WITH MAX_TABLE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR', MAX(SIZE_OF_COLONY) AS 'MAX_SIZE'
    FROM ECOLI_DATA
    GROUP BY YEAR
)
SELECT
    YEAR(ED.DIFFERENTIATION_DATE) AS 'YEAR'
    , MT.MAX_SIZE - ED.SIZE_OF_COLONY AS 'YEAR_DEV'
    , ID
FROM
    ECOLI_DATA ED
JOIN
    MAX_TABLE MT
ON
    YEAR(ED.DIFFERENTIATION_DATE) = MT.YEAR
ORDER BY
    1, 2