SELECT FI.ID, FNI.FISH_NAME, T.LENGTH
FROM (
    SELECT FISH_TYPE, MAX(LENGTH) AS 'LENGTH'
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) T
JOIN FISH_INFO FI ON FI.FISH_TYPE = T.FISH_TYPE AND FI.LENGTH = T.LENGTH
JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = T.FISH_TYPE
ORDER BY FI.ID