# 부서별 평균 연봉
# 부서별로 부서 ID, 영문 부서명, 평균 연봉 조회

SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(E.SAL), 0) AS 'AVG_SAL'
FROM HR_DEPARTMENT D
INNER JOIN HR_EMPLOYEES E
ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_ID
ORDER BY 3 DESC