SELECT B.CATEGORY, SUM(BS.SALES) AS 'TOTAL_SALES'
FROM (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 1
) BS
JOIN BOOK B USING(BOOK_ID)
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY