# 식품분류별 가격이 제일 비싼 식품
# 분류, 가격, 이름 조회

SELECT FM.CATEGORY, FM.MAX_PRICE, F.PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) AS 'MAX_PRICE'
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) FM
LEFT OUTER JOIN FOOD_PRODUCT F
ON FM.CATEGORY = F.CATEGORY
AND F.PRICE = FM.MAX_PRICE
ORDER BY FM.MAX_PRICE DESC